theme: jekyll-theme-midnight
title: B.C. Ferrari Home Page
description: >
    I'm currently a Physics PhD candidate at the University of
    Central Florida, working under Dr. Christopher J. Bennett.
    My interests are in Computational Quantum Chemistry, Space Weathering,
    Surface Science and Radiative Transfer.
