[general]
author = "Brian C. Ferrari"
pronouns = "(he/him)"
my_picture = "/assets/figs/me.jpg"
my_bio = "Chemistry PhD Candidate at Leiden University"

[links]
scholar = [ "https://scholar.google.com/citations?user=col48NcAAAAJ&hl=en", "fa fa-graduation-cap" ]
github = [ "https://github.com/Cavenfish", "fa fa-brands fa-github" ]
orcid = [ "https://orcid.org/0000-0002-7416-8629", "fa fa-brands fa-orcid" ]
linkedin = [ "https://www.linkedin.com/in/brian-ferrari-001b8a163/", "fa fa-brands fa-linkedin" ]
researchgate = [ "https://www.researchgate.net/profile/Brian-Ferrari-2?ev=hdr_xprf", "fa fa-brands fa-researchgate" ]