title = "B.C. Ferrari"
base_url = "https://Cavenfish.github.io"
theme = "xuan"

compile_sass = true
build_search_index = false

taxonomies = [{ name = "tags", feed = true }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[extra.nav]
auto_hide = true
show_feed = true
show_theme_switcher = true
show_repo = false

# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
    { url = "@/blog/_index.md", name = "Blog" },
    { url = "@/software/_index.md", name = "Personal Projects" },
]

[extra.footer]
links = []

# Social links in the footer.
# Any URL-encoded SVG can be used as an icon.
# https://simpleicons.org is the recommended source of SVG icons.
# For URL encoding use https://yoksel.github.io/url-encoder/.
# Make sure that "external quotes" are set to "double".
socials = [
    { url = "https://github.com/Cavenfish", name = "GitHub", icon = "fa fa-brands fa-github" },
    { url = "https://www.linkedin.com/in/brian-ferrari-001b8a163/", name = "LinkedIn", icon = "fa fa-brands fa-linkedin" },
]

show_copyright = false
show_powered_by = true
show_source = false
